kind = "mobile"
previewPath = "/"
title = "SmartEVP+ Driver"
version = "1.0.0"
id = "artifacts/smartevp-driver"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19651

[services.development]
run = "pnpm --filter @workspace/smartevp-driver run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/smartevp-driver", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/smartevp-driver", "run", "serve" ]

[services.env]
PORT = "19651"
BASE_PATH = "/"
